version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lending-borrowing-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/api
    restart: unless-stopped
