/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ExploreRouteImport } from './routes/explore/route'
import { Route as ExploreIndexImport } from './routes/explore/index'
import { Route as authSignInImport } from './routes/(auth)/sign-in'
import { Route as authOtpImport } from './routes/(auth)/otp'
import { Route as auth500Import } from './routes/(auth)/500'
import { Route as ExploreUserIndexImport } from './routes/explore/user/index'
import { Route as ExploreAllIndexImport } from './routes/explore/all/index'

// Create Virtual Routes

const errors503LazyImport = createFileRoute('/(errors)/503')()
const errors500LazyImport = createFileRoute('/(errors)/500')()
const errors404LazyImport = createFileRoute('/(errors)/404')()
const errors403LazyImport = createFileRoute('/(errors)/403')()
const errors401LazyImport = createFileRoute('/(errors)/401')()
const authSignUpLazyImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyImport = createFileRoute(
  '/(auth)/forgot-password',
)()
const ExploreSettingsRouteLazyImport = createFileRoute('/explore/settings')()
const ExploreTasksIndexLazyImport = createFileRoute('/explore/tasks/')()
const ExploreSettingsIndexLazyImport = createFileRoute('/explore/settings/')()
const ExploreHelpCenterIndexLazyImport = createFileRoute(
  '/explore/help-center/',
)()
const ExploreChatsIndexLazyImport = createFileRoute('/explore/chats/')()
const ExploreAppsIndexLazyImport = createFileRoute('/explore/apps/')()
const ExploreSettingsNotificationsLazyImport = createFileRoute(
  '/explore/settings/notifications',
)()
const ExploreSettingsDisplayLazyImport = createFileRoute(
  '/explore/settings/display',
)()
const ExploreSettingsAppearanceLazyImport = createFileRoute(
  '/explore/settings/appearance',
)()
const ExploreSettingsAccountLazyImport = createFileRoute(
  '/explore/settings/account',
)()

// Create/Update Routes

const ExploreRouteRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRoute,
} as any)

const ExploreIndexRoute = ExploreIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreRouteRoute,
} as any)

const errors503LazyRoute = errors503LazyImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))

const errors500LazyRoute = errors500LazyImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))

const errors404LazyRoute = errors404LazyImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))

const errors403LazyRoute = errors403LazyImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))

const errors401LazyRoute = errors401LazyImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))

const authSignUpLazyRoute = authSignUpLazyImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))

const authSignIn2LazyRoute = authSignIn2LazyImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))

const authForgotPasswordLazyRoute = authForgotPasswordLazyImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )

const ExploreSettingsRouteLazyRoute = ExploreSettingsRouteLazyImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ExploreRouteRoute,
} as any).lazy(() =>
  import('./routes/explore/settings/route.lazy').then((d) => d.Route),
)

const authSignInRoute = authSignInImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const authOtpRoute = authOtpImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRoute,
} as any)

const auth500Route = auth500Import.update({
  id: '/(auth)/500',
  path: '/500',
  getParentRoute: () => rootRoute,
} as any)

const ExploreTasksIndexLazyRoute = ExploreTasksIndexLazyImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => ExploreRouteRoute,
} as any).lazy(() =>
  import('./routes/explore/tasks/index.lazy').then((d) => d.Route),
)

const ExploreSettingsIndexLazyRoute = ExploreSettingsIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExploreSettingsRouteLazyRoute,
} as any).lazy(() =>
  import('./routes/explore/settings/index.lazy').then((d) => d.Route),
)

const ExploreHelpCenterIndexLazyRoute = ExploreHelpCenterIndexLazyImport.update(
  {
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => ExploreRouteRoute,
  } as any,
).lazy(() =>
  import('./routes/explore/help-center/index.lazy').then((d) => d.Route),
)

const ExploreChatsIndexLazyRoute = ExploreChatsIndexLazyImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => ExploreRouteRoute,
} as any).lazy(() =>
  import('./routes/explore/chats/index.lazy').then((d) => d.Route),
)

const ExploreAppsIndexLazyRoute = ExploreAppsIndexLazyImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => ExploreRouteRoute,
} as any).lazy(() =>
  import('./routes/explore/apps/index.lazy').then((d) => d.Route),
)

const ExploreUserIndexRoute = ExploreUserIndexImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => ExploreRouteRoute,
} as any)

const ExploreAllIndexRoute = ExploreAllIndexImport.update({
  id: '/all/',
  path: '/all/',
  getParentRoute: () => ExploreRouteRoute,
} as any)

const ExploreSettingsNotificationsLazyRoute =
  ExploreSettingsNotificationsLazyImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ExploreSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/explore/settings/notifications.lazy').then((d) => d.Route),
  )

const ExploreSettingsDisplayLazyRoute = ExploreSettingsDisplayLazyImport.update(
  {
    id: '/display',
    path: '/display',
    getParentRoute: () => ExploreSettingsRouteLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/explore/settings/display.lazy').then((d) => d.Route),
)

const ExploreSettingsAppearanceLazyRoute =
  ExploreSettingsAppearanceLazyImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => ExploreSettingsRouteLazyRoute,
  } as any).lazy(() =>
    import('./routes/explore/settings/appearance.lazy').then((d) => d.Route),
  )

const ExploreSettingsAccountLazyRoute = ExploreSettingsAccountLazyImport.update(
  {
    id: '/account',
    path: '/account',
    getParentRoute: () => ExploreSettingsRouteLazyRoute,
  } as any,
).lazy(() =>
  import('./routes/explore/settings/account.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/500': {
      id: '/(auth)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof auth500Import
      parentRoute: typeof rootRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInImport
      parentRoute: typeof rootRoute
    }
    '/explore/settings': {
      id: '/explore/settings'
      path: '/settings'
      fullPath: '/explore/settings'
      preLoaderRoute: typeof ExploreSettingsRouteLazyImport
      parentRoute: typeof ExploreRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyImport
      parentRoute: typeof rootRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyImport
      parentRoute: typeof rootRoute
    }
    '/explore/': {
      id: '/explore/'
      path: '/'
      fullPath: '/explore/'
      preLoaderRoute: typeof ExploreIndexImport
      parentRoute: typeof ExploreRouteImport
    }
    '/explore/settings/account': {
      id: '/explore/settings/account'
      path: '/account'
      fullPath: '/explore/settings/account'
      preLoaderRoute: typeof ExploreSettingsAccountLazyImport
      parentRoute: typeof ExploreSettingsRouteLazyImport
    }
    '/explore/settings/appearance': {
      id: '/explore/settings/appearance'
      path: '/appearance'
      fullPath: '/explore/settings/appearance'
      preLoaderRoute: typeof ExploreSettingsAppearanceLazyImport
      parentRoute: typeof ExploreSettingsRouteLazyImport
    }
    '/explore/settings/display': {
      id: '/explore/settings/display'
      path: '/display'
      fullPath: '/explore/settings/display'
      preLoaderRoute: typeof ExploreSettingsDisplayLazyImport
      parentRoute: typeof ExploreSettingsRouteLazyImport
    }
    '/explore/settings/notifications': {
      id: '/explore/settings/notifications'
      path: '/notifications'
      fullPath: '/explore/settings/notifications'
      preLoaderRoute: typeof ExploreSettingsNotificationsLazyImport
      parentRoute: typeof ExploreSettingsRouteLazyImport
    }
    '/explore/all/': {
      id: '/explore/all/'
      path: '/all'
      fullPath: '/explore/all'
      preLoaderRoute: typeof ExploreAllIndexImport
      parentRoute: typeof ExploreRouteImport
    }
    '/explore/user/': {
      id: '/explore/user/'
      path: '/user'
      fullPath: '/explore/user'
      preLoaderRoute: typeof ExploreUserIndexImport
      parentRoute: typeof ExploreRouteImport
    }
    '/explore/apps/': {
      id: '/explore/apps/'
      path: '/apps'
      fullPath: '/explore/apps'
      preLoaderRoute: typeof ExploreAppsIndexLazyImport
      parentRoute: typeof ExploreRouteImport
    }
    '/explore/chats/': {
      id: '/explore/chats/'
      path: '/chats'
      fullPath: '/explore/chats'
      preLoaderRoute: typeof ExploreChatsIndexLazyImport
      parentRoute: typeof ExploreRouteImport
    }
    '/explore/help-center/': {
      id: '/explore/help-center/'
      path: '/help-center'
      fullPath: '/explore/help-center'
      preLoaderRoute: typeof ExploreHelpCenterIndexLazyImport
      parentRoute: typeof ExploreRouteImport
    }
    '/explore/settings/': {
      id: '/explore/settings/'
      path: '/'
      fullPath: '/explore/settings/'
      preLoaderRoute: typeof ExploreSettingsIndexLazyImport
      parentRoute: typeof ExploreSettingsRouteLazyImport
    }
    '/explore/tasks/': {
      id: '/explore/tasks/'
      path: '/tasks'
      fullPath: '/explore/tasks'
      preLoaderRoute: typeof ExploreTasksIndexLazyImport
      parentRoute: typeof ExploreRouteImport
    }
  }
}

// Create and export the route tree

interface ExploreSettingsRouteLazyRouteChildren {
  ExploreSettingsAccountLazyRoute: typeof ExploreSettingsAccountLazyRoute
  ExploreSettingsAppearanceLazyRoute: typeof ExploreSettingsAppearanceLazyRoute
  ExploreSettingsDisplayLazyRoute: typeof ExploreSettingsDisplayLazyRoute
  ExploreSettingsNotificationsLazyRoute: typeof ExploreSettingsNotificationsLazyRoute
  ExploreSettingsIndexLazyRoute: typeof ExploreSettingsIndexLazyRoute
}

const ExploreSettingsRouteLazyRouteChildren: ExploreSettingsRouteLazyRouteChildren =
  {
    ExploreSettingsAccountLazyRoute: ExploreSettingsAccountLazyRoute,
    ExploreSettingsAppearanceLazyRoute: ExploreSettingsAppearanceLazyRoute,
    ExploreSettingsDisplayLazyRoute: ExploreSettingsDisplayLazyRoute,
    ExploreSettingsNotificationsLazyRoute:
      ExploreSettingsNotificationsLazyRoute,
    ExploreSettingsIndexLazyRoute: ExploreSettingsIndexLazyRoute,
  }

const ExploreSettingsRouteLazyRouteWithChildren =
  ExploreSettingsRouteLazyRoute._addFileChildren(
    ExploreSettingsRouteLazyRouteChildren,
  )

interface ExploreRouteRouteChildren {
  ExploreSettingsRouteLazyRoute: typeof ExploreSettingsRouteLazyRouteWithChildren
  ExploreIndexRoute: typeof ExploreIndexRoute
  ExploreAllIndexRoute: typeof ExploreAllIndexRoute
  ExploreUserIndexRoute: typeof ExploreUserIndexRoute
  ExploreAppsIndexLazyRoute: typeof ExploreAppsIndexLazyRoute
  ExploreChatsIndexLazyRoute: typeof ExploreChatsIndexLazyRoute
  ExploreHelpCenterIndexLazyRoute: typeof ExploreHelpCenterIndexLazyRoute
  ExploreTasksIndexLazyRoute: typeof ExploreTasksIndexLazyRoute
}

const ExploreRouteRouteChildren: ExploreRouteRouteChildren = {
  ExploreSettingsRouteLazyRoute: ExploreSettingsRouteLazyRouteWithChildren,
  ExploreIndexRoute: ExploreIndexRoute,
  ExploreAllIndexRoute: ExploreAllIndexRoute,
  ExploreUserIndexRoute: ExploreUserIndexRoute,
  ExploreAppsIndexLazyRoute: ExploreAppsIndexLazyRoute,
  ExploreChatsIndexLazyRoute: ExploreChatsIndexLazyRoute,
  ExploreHelpCenterIndexLazyRoute: ExploreHelpCenterIndexLazyRoute,
  ExploreTasksIndexLazyRoute: ExploreTasksIndexLazyRoute,
}

const ExploreRouteRouteWithChildren = ExploreRouteRoute._addFileChildren(
  ExploreRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/explore': typeof ExploreRouteRouteWithChildren
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/explore/settings': typeof ExploreSettingsRouteLazyRouteWithChildren
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/explore/': typeof ExploreIndexRoute
  '/explore/settings/account': typeof ExploreSettingsAccountLazyRoute
  '/explore/settings/appearance': typeof ExploreSettingsAppearanceLazyRoute
  '/explore/settings/display': typeof ExploreSettingsDisplayLazyRoute
  '/explore/settings/notifications': typeof ExploreSettingsNotificationsLazyRoute
  '/explore/all': typeof ExploreAllIndexRoute
  '/explore/user': typeof ExploreUserIndexRoute
  '/explore/apps': typeof ExploreAppsIndexLazyRoute
  '/explore/chats': typeof ExploreChatsIndexLazyRoute
  '/explore/help-center': typeof ExploreHelpCenterIndexLazyRoute
  '/explore/settings/': typeof ExploreSettingsIndexLazyRoute
  '/explore/tasks': typeof ExploreTasksIndexLazyRoute
}

export interface FileRoutesByTo {
  '/500': typeof errors500LazyRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/503': typeof errors503LazyRoute
  '/explore': typeof ExploreIndexRoute
  '/explore/settings/account': typeof ExploreSettingsAccountLazyRoute
  '/explore/settings/appearance': typeof ExploreSettingsAppearanceLazyRoute
  '/explore/settings/display': typeof ExploreSettingsDisplayLazyRoute
  '/explore/settings/notifications': typeof ExploreSettingsNotificationsLazyRoute
  '/explore/all': typeof ExploreAllIndexRoute
  '/explore/user': typeof ExploreUserIndexRoute
  '/explore/apps': typeof ExploreAppsIndexLazyRoute
  '/explore/chats': typeof ExploreChatsIndexLazyRoute
  '/explore/help-center': typeof ExploreHelpCenterIndexLazyRoute
  '/explore/settings': typeof ExploreSettingsIndexLazyRoute
  '/explore/tasks': typeof ExploreTasksIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/explore': typeof ExploreRouteRouteWithChildren
  '/(auth)/500': typeof auth500Route
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/explore/settings': typeof ExploreSettingsRouteLazyRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/explore/': typeof ExploreIndexRoute
  '/explore/settings/account': typeof ExploreSettingsAccountLazyRoute
  '/explore/settings/appearance': typeof ExploreSettingsAppearanceLazyRoute
  '/explore/settings/display': typeof ExploreSettingsDisplayLazyRoute
  '/explore/settings/notifications': typeof ExploreSettingsNotificationsLazyRoute
  '/explore/all/': typeof ExploreAllIndexRoute
  '/explore/user/': typeof ExploreUserIndexRoute
  '/explore/apps/': typeof ExploreAppsIndexLazyRoute
  '/explore/chats/': typeof ExploreChatsIndexLazyRoute
  '/explore/help-center/': typeof ExploreHelpCenterIndexLazyRoute
  '/explore/settings/': typeof ExploreSettingsIndexLazyRoute
  '/explore/tasks/': typeof ExploreTasksIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/explore'
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/explore/settings'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/explore/'
    | '/explore/settings/account'
    | '/explore/settings/appearance'
    | '/explore/settings/display'
    | '/explore/settings/notifications'
    | '/explore/all'
    | '/explore/user'
    | '/explore/apps'
    | '/explore/chats'
    | '/explore/help-center'
    | '/explore/settings/'
    | '/explore/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/500'
    | '/otp'
    | '/sign-in'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/503'
    | '/explore'
    | '/explore/settings/account'
    | '/explore/settings/appearance'
    | '/explore/settings/display'
    | '/explore/settings/notifications'
    | '/explore/all'
    | '/explore/user'
    | '/explore/apps'
    | '/explore/chats'
    | '/explore/help-center'
    | '/explore/settings'
    | '/explore/tasks'
  id:
    | '__root__'
    | '/explore'
    | '/(auth)/500'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/explore/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/explore/'
    | '/explore/settings/account'
    | '/explore/settings/appearance'
    | '/explore/settings/display'
    | '/explore/settings/notifications'
    | '/explore/all/'
    | '/explore/user/'
    | '/explore/apps/'
    | '/explore/chats/'
    | '/explore/help-center/'
    | '/explore/settings/'
    | '/explore/tasks/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ExploreRouteRoute: typeof ExploreRouteRouteWithChildren
  auth500Route: typeof auth500Route
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  ExploreRouteRoute: ExploreRouteRouteWithChildren,
  auth500Route: auth500Route,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/explore",
        "/(auth)/500",
        "/(auth)/otp",
        "/(auth)/sign-in",
        "/(auth)/forgot-password",
        "/(auth)/sign-in-2",
        "/(auth)/sign-up",
        "/(errors)/401",
        "/(errors)/403",
        "/(errors)/404",
        "/(errors)/500",
        "/(errors)/503"
      ]
    },
    "/explore": {
      "filePath": "explore/route.tsx",
      "children": [
        "/explore/settings",
        "/explore/",
        "/explore/all/",
        "/explore/user/",
        "/explore/apps/",
        "/explore/chats/",
        "/explore/help-center/",
        "/explore/tasks/"
      ]
    },
    "/(auth)/500": {
      "filePath": "(auth)/500.tsx"
    },
    "/(auth)/otp": {
      "filePath": "(auth)/otp.tsx"
    },
    "/(auth)/sign-in": {
      "filePath": "(auth)/sign-in.tsx"
    },
    "/explore/settings": {
      "filePath": "explore/settings/route.lazy.tsx",
      "parent": "/explore",
      "children": [
        "/explore/settings/account",
        "/explore/settings/appearance",
        "/explore/settings/display",
        "/explore/settings/notifications",
        "/explore/settings/"
      ]
    },
    "/(auth)/forgot-password": {
      "filePath": "(auth)/forgot-password.lazy.tsx"
    },
    "/(auth)/sign-in-2": {
      "filePath": "(auth)/sign-in-2.lazy.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.lazy.tsx"
    },
    "/(errors)/401": {
      "filePath": "(errors)/401.lazy.tsx"
    },
    "/(errors)/403": {
      "filePath": "(errors)/403.lazy.tsx"
    },
    "/(errors)/404": {
      "filePath": "(errors)/404.lazy.tsx"
    },
    "/(errors)/500": {
      "filePath": "(errors)/500.lazy.tsx"
    },
    "/(errors)/503": {
      "filePath": "(errors)/503.lazy.tsx"
    },
    "/explore/": {
      "filePath": "explore/index.tsx",
      "parent": "/explore"
    },
    "/explore/settings/account": {
      "filePath": "explore/settings/account.lazy.tsx",
      "parent": "/explore/settings"
    },
    "/explore/settings/appearance": {
      "filePath": "explore/settings/appearance.lazy.tsx",
      "parent": "/explore/settings"
    },
    "/explore/settings/display": {
      "filePath": "explore/settings/display.lazy.tsx",
      "parent": "/explore/settings"
    },
    "/explore/settings/notifications": {
      "filePath": "explore/settings/notifications.lazy.tsx",
      "parent": "/explore/settings"
    },
    "/explore/all/": {
      "filePath": "explore/all/index.tsx",
      "parent": "/explore"
    },
    "/explore/user/": {
      "filePath": "explore/user/index.tsx",
      "parent": "/explore"
    },
    "/explore/apps/": {
      "filePath": "explore/apps/index.lazy.tsx",
      "parent": "/explore"
    },
    "/explore/chats/": {
      "filePath": "explore/chats/index.lazy.tsx",
      "parent": "/explore"
    },
    "/explore/help-center/": {
      "filePath": "explore/help-center/index.lazy.tsx",
      "parent": "/explore"
    },
    "/explore/settings/": {
      "filePath": "explore/settings/index.lazy.tsx",
      "parent": "/explore/settings"
    },
    "/explore/tasks/": {
      "filePath": "explore/tasks/index.lazy.tsx",
      "parent": "/explore"
    }
  }
}
ROUTE_MANIFEST_END */
