name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Show Forge version
        working-directory: contracts
        run: |
          forge --version --root 

      - name: Run Forge fmt
        working-directory: contracts
        run: |
          forge fmt --check --root 
        id: fmt

      - name: Run Forge build
        working-directory: contracts
        run: |
          forge build --sizes --root 
        id: build

      - name: Run Forge tests
        working-directory: contracts
        run: |
          forge test -vvv --root 
        id: test
